### ISSUE TITLE
Suggest a minor change in one line of code in cell 9

### ISSUE THREAD

**Issue by shirishr** [MatthewYancey/IndyML#1]
In cell 9 of the notebook: 
line:
files = glob.glob('/home/matt/Repos/simpsons/data_raw/color/validation/' + folders[i] + '/*.jpg')

be changed to:
files = glob.glob(validation_data_pth+ folders[i] + '/*.jpg')

**Comment by MatthewYancey** [comment]
Thanks for pointing that out, I'll make the switch
